import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useFasttrackPrice } from '../hooks/FastTrackHooks';
import { getCookies, getCookie, setCookies, removeCookies } from 'cookies-next'
// import styles from '@/styles/Home.module.css'

const inter = Inter( { subsets: [ 'latin' ] } )

// export const getServerSideProps = ( { req, res } ) => {
// 	return { props: {} }
// }

export default function Home() {

	const fasttrackAppid = getCookie( 'fasttrack-appid' ),
		fasttrackToken = getCookie( 'fasttrack-token' )

	const { data } = useFasttrackPrice( 'GNT', fasttrackAppid, fasttrackToken )
	console.log('%c 🍝 data: ', 'font-size:20px;background-color: #3F7CFF;color:#fff;', data);

	return <>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main>
			
		</main>
	</>

}
